services:
  corosync-qnetd:
    image: corosync-qnetd
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qnetd
    environment:
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "5403:5403"
      - "22:22"
    volumes:
      - ./nssdb/:/etc/corosync/qnetd/nssdb
      - ./ssh/:/root/ssh_host_keys
    restart: unless-stopped